### ISSUE TITLE
no navigation buttons (older/newer)

### ISSUE THREAD

**Issue by jcaude** [tranduyhung/grav-skeleton-clean-blog#10]
Hello,

I have used the skeleton but not old/newer posts button appear, unlike the demo site.. it there anything to do on the general settings or site settings ?

thanks

**Comment by tranduyhung** [comment]
The buttons belong to Grav's pagination. Ensure you've configured the collection and its pagination, here is [an example](https://github.com/tranduyhung/grav-skeleton-clean-blog/blob/master/pages/01.home/blog.md).

**Comment by jcaude** [comment]
Sorry, forget to thx you.. it works now.
