### ISSUE TITLE
Problems with Featherlight plugin

### ISSUE THREAD

**Issue by bartoszwanot** [tranduyhung/grav-skeleton-clean-blog#2]
Hi

I'm using your template for my website and I've got problem with Featherlight plugin.  I've installed and activated as the manual says. However it's not working as it should - images are showing in the tab, not in the lightbox. You can check it here: http://sugoi.com.pl/beta/new-nintendo-2ds-xl-odswiezona-przenosna-konsola (images are at the end of the article).

Code in the article is:
`![](2ds-dq2.jpg?lightbox=1024&cropResize=200,200) ![](2ds-dq1.jpg?lightbox=1024&cropResize=200,200) ![](2ds-dq3.jpg?lightbox=1024&cropResize=200,200)`

And here is configuration of Featherlight from featherlight.yaml file:

```
enabled: true                 # global enable/disable the entire plugin
active: true                  # if the plugin is active and JS/CSS should be loaded
gallery: false                # enable/disable the gallery extension
requirejs: false              # output to an AMD module
openSpeed: 250                # open speed in ms
closeSpeed: 250               # close speed in ms
closeOnClick: background      # background|anywhere|false
closeOnEsc: true              # true|false on hitting Esc key
root: body                    # where to append featherlights
initTemplate: plugin://featherlight/js/featherlight.init.js
```

Any ideas what I have done wrong? Maybe there is some conflict between your template and this plugin?

**Comment by tranduyhung** [comment]
Hi,

Please update the theme to version 1.3.1, I have just fixed it.

**Comment by bartoszwanot** [comment]
Works like a charm - thanks for quick fix!
