### ISSUE TITLE
No image when sharing post

### ISSUE THREAD

**Issue by bartoszwanot** [tranduyhung/grav-skeleton-clean-blog#3]
Hello,

When I try to share my post on Google+, Twitter or Facebook, the header image of post is not loaded to the preview window. Can you please fix it?

**Comment by tranduyhung** [comment]
Hi,

Please try version 1.4.0, I added Open Graph to it.

**Comment by bartoszwanot** [comment]
Hi @tranduyhung ,

Now it works without a problem. Can you also add as optional to add og:description from subheading text to the code?

**Comment by bartoszwanot** [comment]
Everything was solved thanks to plugin SEO.
