### ISSUE TITLE
Mobile navigation and link in tittle not working

### ISSUE THREAD

**Issue by bartoszwanot** [tranduyhung/grav-skeleton-clean-blog#5]
Hi,

I found out that navigation panel is not workin correctly on smartphone devices - it isn't collapsing to show subpages. What is more - the link in nav header is not working as well (it's not redirecting to homepage). Can you check it, please? You can check both of my websites that are using your template:

- [geekretro.pl](http://geekretro.pl)
- [sugoi.com.pl](http://sugoi.com.pl)

Thanks in advance.

**Comment by tranduyhung** [comment]
Thank you for reporting this!

In user/themes/clean-blog/css/clean-blog.min.css you search for
````
.navbar-custom {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    z-index: 3
}
````

and change the value 3 of z-index to 100, this will fix the issue. I will release a new version to fix this.

**Comment by bartoszwanot** [comment]
Works like a charm - thanks for quick reply.
