### ISSUE TITLE
Sub-Title of Posting has 'on' wrong

### ISSUE THREAD

**Issue by DiesDasJenes** [tranduyhung/grav-skeleton-clean-blog#6]
Hi,
In my Blog it writes a 1 instead of 'on'. I used this skeleton without any plugins. A fresh Configuration as you could say. Do you know a way to fix it? Thanks. 

Example:
Posted by Person X 1 19th Jul 2017

**Comment by tranduyhung** [comment]
I can't see this problem here. What are your Grav version and Clean Blog theme version?

**Comment by DiesDasJenes** [comment]
Hi, thanks for the answer. The version of GetGrav is v1.3.8 and Clean-Blog has the version v1.4.1

**Comment by tranduyhung** [comment]
I have the same versions here I don't see this problem at all.

Please check user/themes/clean-blog/languages.yaml file, is the line 39:

        POST_ON: on

?

If it is, I can help you check if you could zip your "user" folder and send it to flatfiledeveloper@gmail.com.

**Comment by DiesDasJenes** [comment]
Hi,
with the help of tranduyhung i added the German language support, here is what I change in user/config/system.yaml

languages:
  include_default_lang: true
  translations: true
  translations_fallback: true
  session_store_active: false
  http_accept_language: false
  override_locale: false
  **supported:
    - de**

Now i get:
Person X am 13th Jun 2017

Thanks for the help. :)
