### ISSUE TITLE
Showing tags in blog post

### ISSUE THREAD

**Issue by bartoszwanot** [tranduyhung/grav-skeleton-clean-blog#7]
Hi,

I'm trying to figure out how to show tags in each blog post. By tags I mean the one that are defined in taxonomy. Could you please help me what should I add to item.html.twig to show it?

**Comment by tranduyhung** [comment]
You can find lot of useful code in Antimatter theme. Here is how Antimatter shows tags:

```
        {% if page.taxonomy.tag %}
        <span class="tags">
            {% for tag in page.taxonomy.tag %}
            <a href="{{ blog.url|rtrim('/') }}/tag{{ config.system.param_sep }}{{ tag }}" class="p-category">{{ tag }}</a>
            {% endfor %}
        </span>
        {% endif %}
```

The file is user/themes/antimatter/templates/partials/blog_item.html.twig. Ensure you have ```blog``` variable which is the page of your blog, you can define it by yourself.

**Comment by bartoszwanot** [comment]
Works out of the box - thanks 👍
