### ISSUE TITLE
Not up to date

### ISSUE THREAD

**Issue by itsissaissa** [tranduyhung/grav-skeleton-clean-blog#9]
Hello, this doesn't install cleanly with the admin controlpanel plugin.

**Comment by tranduyhung** [comment]
Hi,

You can install Admin plugin if you need it, it only takes a few seconds. Not all Grav users use Admin plugin.

**Comment by itsissaissa** [comment]
No I meant it doesn't work with it. I get an error on this line in the login plugin:
            $users = Grav::instance()['accounts'];

**Comment by tranduyhung** [comment]
You can update Login plugin (and others) to the latest releases. If you know command line, here is the command you can use: https://learn.getgrav.org/16/cli-console/grav-cli-gpm#update

**Comment by itsissaissa** [comment]
I am not entirely sure how to access my server's command line to type in these commands. I am trying to do everything via FTP. My latest attempt is telling me the same thing you are which is to run the command!

Also thank you for actually responding. I feel like I'm asking the wrong questions and you're still being helpful.
